# Redis is used for session tokens and Resque jobs.
development:
  redis: &common
    id: 'pibi'
    db: 0
    host: 'localhost'
    port: 6379
    password:
    timeout: 5.0
    tcp_keepalive: 0

production:
  redis:
    <<: *common

test:
  redis:
    <<: *common
